name: Build Template

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    uses: thomasm-ttd/SharedWorkflows/.github/workflows/sharedbuild.yaml@main
