name: Shared Maven Build And Test

on:
  workflow_call:

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: mvn -B clean compile test
